hw08/events/lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router


  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.FetchSession

  end

  pipeline :api do
    plug :accepts, ["json"]
  end



  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/events", EventController
    resources "/invites", InviteController,
      only: [:edit, :create, :new, :index, :update]
    resources "/comments", CommentController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

hw08/events/lib/events/application.ex
defmodule Events.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Events.Repo,
      # Start the Telemetry supervisor
      EventsWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Events.PubSub},
      # Start the Endpoint (http/https)
      EventsWeb.Endpoint
      # Start a worker by calling: Events.Worker.start_link(arg)
      # {Events.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Events.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EventsWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

hw08/events/lib/events/cal_events.ex
defmodule Events.CalEvents do
  @moduledoc """
  The CalEvents context.
  """

  import Ecto.Query, warn: false
  alias Events.Repo

  alias Events.CalEvents.Event

  @doc """
  Returns the list of events.

  ## Examples

      iex> list_events()
      [%Event{}, ...]

  """
  def list_events do
    Repo.all(Event)
  end

  @doc """
  Gets a single event.

  Raises `Ecto.NoResultsError` if the Event does not exist.

  ## Examples

      iex> get_event!(123)
      %Event{}

      iex> get_event!(456)
      ** (Ecto.NoResultsError)

  """
  def get_event!(id), do: Repo.get!(Event, id)

  @doc """
  Creates a event.

  ## Examples

      iex> create_event(%{field: value})
      {:ok, %Event{}}

      iex> create_event(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_event(attrs \\ %{}) do
    %Event{}
    |> Event.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a event.

  ## Examples

      iex> update_event(event, %{field: new_value})
      {:ok, %Event{}}

      iex> update_event(event, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_event(%Event{} = event, attrs) do
    event
    |> Event.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a event.

  ## Examples

      iex> delete_event(event)
      {:ok, %Event{}}

      iex> delete_event(event)
      {:error, %Ecto.Changeset{}}

  """
  def delete_event(%Event{} = event) do
    Repo.delete(event)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking event changes.

  ## Examples

      iex> change_event(event)
      %Ecto.Changeset{data: %Event{}}

  """
  def change_event(%Event{} = event, attrs \\ %{}) do
    Event.changeset(event, attrs)
  end

  def is_invitee?(event_id, user) do
    if user == nil do
      false
    else
      query = from i in Events.Invites.Invite,
                   where: i.event_id == ^event_id and i.invitee == ^user.email

      results = Repo.all(query)

      if Enum.empty?(results) do
        false
      else
        true
      end
    end
  end

  def is_owner?(event_id, user) do
    if user == nil do
      false
    else
      event = get_event!(event_id)
      event.user_id == user.id
    end
  end
end

hw08/events/lib/events/cal_events/event.ex
defmodule Events.CalEvents.Event do
  use Ecto.Schema
  import Ecto.Changeset

  schema "events" do
    field :date, :naive_datetime
    field :description, :string
    field :name, :string
    belongs_to :user, Events.Users.User
    has_many :comments, Events.Comments.Comment
    timestamps()
  end

  @doc false
  def changeset(event, attrs) do
    event
    |> cast(attrs, [:name, :date, :description, :user_id])
    |> validate_required([:name, :date, :description, :user_id])
  end
end

hw08/events/lib/events/comments.ex
defmodule Events.Comments do
  @moduledoc """
  The Comments context.
  """

  import Ecto.Query, warn: false
  alias Events.Repo

  alias Events.Comments.Comment

  @doc """
  Returns the list of comments.

  ## Examples

      iex> list_comments()
      [%Comment{}, ...]

  """
  def list_comments do
    Repo.all(Comment)
  end

  def list_comments_for_event(id) do
    query = from c in Comment,
                 where: c.event_id == ^id

    Repo.all(query)
  end

  @doc """
  Gets a single comment.

  Raises `Ecto.NoResultsError` if the Comment does not exist.

  ## Examples

      iex> get_comment!(123)
      %Comment{}

      iex> get_comment!(456)
      ** (Ecto.NoResultsError)

  """
  def get_comment!(id), do: Repo.get!(Comment, id)

  @doc """
  Creates a comment.

  ## Examples

      iex> create_comment(%{field: value})
      {:ok, %Comment{}}

      iex> create_comment(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_comment(attrs \\ %{}) do
    %Comment{}
    |> Comment.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a comment.

  ## Examples

      iex> update_comment(comment, %{field: new_value})
      {:ok, %Comment{}}

      iex> update_comment(comment, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_comment(%Comment{} = comment, attrs) do
    comment
    |> Comment.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a comment.

  ## Examples

      iex> delete_comment(comment)
      {:ok, %Comment{}}

      iex> delete_comment(comment)
      {:error, %Ecto.Changeset{}}

  """
  def delete_comment(%Comment{} = comment) do
    Repo.delete(comment)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking comment changes.

  ## Examples

      iex> change_comment(comment)
      %Ecto.Changeset{data: %Comment{}}

  """
  def change_comment(%Comment{} = comment, attrs \\ %{}) do
    Comment.changeset(comment, attrs)
  end

  def is_author?(comment_id, user) do
    if user == nil do
      false
    else
      comment = get_comment!(comment_id)
      comment.user_id == user.id
    end
  end
end

hw08/events/lib/events/comments/comment.ex
defmodule Events.Comments.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :text, :string
    field :event_id, :id
    field :user_id, :id

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:text, :event_id, :user_id])
    |> validate_required([:text, :event_id, :user_id])
  end
end

hw08/events/lib/events/invites.ex
defmodule Events.Invites do
  @moduledoc """
  The Invites context.
  """

  import Ecto.Query, warn: false
  alias Events.Repo

  alias Events.Invites.Invite

  @doc """
  Returns the list of invites.

  ## Examples

      iex> list_invites()
      [%Invite{}, ...]

  """
  def list_invites do
    Repo.all(Invite)
  end

  @doc """
  Gets a single invite.

  Raises `Ecto.NoResultsError` if the Invite does not exist.

  ## Examples

      iex> get_invite!(123)
      %Invite{}

      iex> get_invite!(456)
      ** (Ecto.NoResultsError)

  """
  def get_invite!(id), do: Repo.get!(Invite, id)

  @doc """
  Creates a invite.

  ## Examples

      iex> create_invite(%{field: value})
      {:ok, %Invite{}}

      iex> create_invite(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_invite(attrs \\ %{}) do
    %Invite{}
    |> Invite.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a invite.

  ## Examples

      iex> update_invite(invite, %{field: new_value})
      {:ok, %Invite{}}

      iex> update_invite(invite, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_invite(%Invite{} = invite, attrs) do
    invite
    |> Invite.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a invite.

  ## Examples

      iex> delete_invite(invite)
      {:ok, %Invite{}}

      iex> delete_invite(invite)
      {:error, %Ecto.Changeset{}}

  """
  def delete_invite(%Invite{} = invite) do
    Repo.delete(invite)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking invite changes.

  ## Examples

      iex> change_invite(invite)
      %Ecto.Changeset{data: %Invite{}}

  """
  def change_invite(%Invite{} = invite, attrs \\ %{}) do
    Invite.changeset(invite, attrs)
  end

  def num_yes_responses(event_id) do
    query = from i in Invite,
                 where: i.event_id == ^event_id and i.response == "Yes",
                 select: count(i)


    Repo.all(query)
  end

  def num_maybe_responses(event_id) do
    query = from i in Invite,
                 where: i.event_id == ^event_id and i.response == "Maybe",
                 select: count(i)


    Repo.all(query)

  end

  def num_no_responses(event_id) do
    query = from i in Invite,
                 where: i.event_id == ^event_id and i.response == "No",
                 select: count(i)


    Repo.all(query)

  end

  def num_havent_responses(event_id) do
    query = from i in Invite,
                 where: i.event_id == ^event_id and i.response == "Haven't Responded",
                 select: count(i)


    Repo.all(query)

  end

  def list_invites_for_event(event_id) do
    query = from i in Invite,
                 where: i.event_id == ^event_id

    Repo.all(query)
  end

  def list_invites_for_email(email) do
    query = from i in Invite,
                 where: i.invitee == ^email

    Repo.all(query)
  end

  def get_invite_for_event_and_email(event_id, email) do
    query = from i in Invite,
                 where: i.invitee == ^email and i.event_id == ^event_id

    results = Repo.all(query)

    if Enum.empty?(results) do
      nil
    else
      hd results
    end
  end
end

hw08/events/lib/events/invites/invite.ex
defmodule Events.Invites.Invite do
  use Ecto.Schema
  import Ecto.Changeset

  schema "invites" do
    field :invitee, :string
    field :response, :string, default: "Haven't Responded"
    field :event_id, :id

    timestamps()
  end

  @doc false
  def changeset(invite, attrs) do
    invite
    |> cast(attrs, [:invitee, :response, :event_id])
    |> validate_required([:invitee, :event_id])
  end
end

hw08/events/lib/events/repo.ex
defmodule Events.Repo do
  use Ecto.Repo,
    otp_app: :events,
    adapter: Ecto.Adapters.Postgres
end

hw08/events/lib/events/users.ex
defmodule Events.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias Events.Repo

  alias Events.Users.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  def get_user(id), do: Repo.get(User, id)

  def get_user_by_email(email) do
    Repo.get_by(User, email: email)
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a user.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{data: %User{}}

  """
  def change_user(%User{} = user, attrs \\ %{}) do
    User.changeset(user, attrs)
  end
end

hw08/events/lib/events/users/user.ex
defmodule Events.Users.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :email, :string
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email])
    |> validate_required([:name, :email])
  end
end

hw08/events/lib/events_web/controllers/event_controller.ex
defmodule EventsWeb.EventController do
  use EventsWeb, :controller

  alias Events.CalEvents
  alias Events.CalEvents.Event
  alias Events.Invites
  alias Events.Comments
  alias Events.Users

  def index(conn, _params) do
    user = conn.assigns[:current_user]
    events = if user == nil do
      []
    else
      CalEvents.list_events()
      |> Enum.filter(fn e -> CalEvents.is_owner?(e.id, user) end)
    end
    render(conn, "index.html", events: events)
  end

  def new(conn, _params) do
    changeset = CalEvents.change_event(%Event{})
    user = conn.assigns[:current_user]
    render(conn, "new.html", changeset: changeset, user_id: user.id)
  end

  def create(conn, %{"event" => event_params}) do
    case CalEvents.create_event(event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    event = CalEvents.get_event!(id)
    invites = Invites.list_invites_for_event(id)

    user = conn.assigns[:current_user]

    if user == nil do
      back = Routes.event_path(conn, :show, event.id)
      conn = assign(conn, :page_back, back)
      conn = put_session(conn, :page_back, back)
      render(conn, "show.html")
    else

      if Events.CalEvents.is_invitee?(id, user) or Events.CalEvents.is_owner?(id, user) do
        yes = Invites.num_yes_responses(id)
              |> hd
        maybe = Invites.num_maybe_responses(id)
                |> hd
        no = Invites.num_no_responses(id)
             |> hd
        havent = Invites.num_havent_responses(id)
                 |> hd

        invite_id = if Events.CalEvents.is_invitee?(id, user) do
          Events.Invites.get_invite_for_event_and_email(id, user.email)
        else
          nil
        end

        comments = Comments.list_comments_for_event(id)
        comment_details = Enum.map(comments, fn c -> {c, Users.get_user!(c.user_id)} end)

        render(
          conn,
          "show.html",
          event: event,
          comment_details: comment_details,
          invites: invites,
          num_yes: yes,
          num_no: no,
          num_maybe: maybe,
          num_havent: havent,
          invite_id: invite_id
        )
      else
        redirect(conn, to: Routes.page_path(conn, :index))
      end
    end
  end

  def edit(conn, %{"id" => id}) do
    event = CalEvents.get_event!(id)
    changeset = CalEvents.change_event(event)
    render(conn, "edit.html", event: event, changeset: changeset)
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = CalEvents.get_event!(id)

    case CalEvents.update_event(event, event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    event = CalEvents.get_event!(id)
    {:ok, _event} = CalEvents.delete_event(event)

    conn
    |> put_flash(:info, "Event deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :index))
  end
end

hw08/events/lib/events_web/views/event_view.ex
defmodule EventsWeb.EventView do
  use EventsWeb, :view
end

hw08/events/lib/events_web/templates/event/edit.html.eex
<h1>Edit Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :update, @event)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :index), class: "btn btn-secondary" %></span>

hw08/events/lib/events_web/templates/event/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>

<div class="form-group">
    <%= hidden_input f, :user_id, value: @user_id %>

    <%= label f, :name, class: "col-form-label"%>
    <%= text_input f, :name, class: "form-control"%>
    <%= error_tag f, :name %>

    <%= label f, :date, class: "col-form-label"%>
    <%= datetime_local_input f, :date, class: "form-control" %>
    <%= error_tag f, :date %>

    <%= label f, :description, class: "col-form-label"%>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
</div>

<div>
    <%= submit "Save", class: "btn btn-primary"%>
</div>
<% end %>

hw08/events/lib/events_web/templates/event/index.html.eex
<h1>Events</h1>
<div>
    <%= if @conn.assigns[:current_user] != nil do %>
    <%= link "New Event", to: Routes.event_path(@conn, :new), class: "btn btn-primary" %>
    <% end %>
    <%= link "Home", to: Routes.page_path(@conn, :index), class: "btn btn-secondary" %>
</div>
<br/>

<div class="container">
    <%= for event <- @events do %>
    <div class="row-cols-xl-1">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><%= event.name %></h5>
                    <p class="card-text"><%= event.date %></p>
                    <p class="card-text"><%= event.description %></p>
                    <%= link "Show", to: Routes.event_path(@conn, :show, event), class: "btn btn-outline-primary" %>
                    <%= link "Edit", to: Routes.event_path(@conn, :edit, event), class: "btn btn-outline-secondary" %>
                    <%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-outline-danger" %>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

hw08/events/lib/events_web/templates/event/new.html.eex
<h1>New Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :index), class: "btn btn-secondary" %></span>

hw08/events/lib/events_web/templates/event/show.html.eex
<h1>Show Event</h1>
<%= if @conn.assigns[:current_user] != nil do%>
<form class="form-group">
    <label class="form-label">Name</label>
    <input type="text" class="form-control" value="<%= @event.name%>" readonly>

    <label class="form-label">Date</label>
    <input type="text" class="form-control" value="<%= @event.date%>" readonly>

    <label class="form-label">Description</label>
    <textarea class="form-control" readonly>
      <%= @event.description%>
    </textarea>
</form>
<%= if Events.CalEvents.is_owner?(@event.id, @conn.assigns[:current_user]) do %>
<span><%= link "Edit", to: Routes.event_path(@conn, :edit, @event), class: "btn btn-primary" %></span>
<span><%= link "Invite", to: Routes.invite_path(@conn, :new, %{event_id: @event.id}), class: "btn btn-secondary" %></span>
<% end %>
<%= if Events.CalEvents.is_invitee?(@event.id, @conn.assigns[:current_user]) do %>
<%= link "Respond", to: Routes.invite_path(@conn, :edit, @invite_id), class: "btn btn-primary" %>
 <% end %>
<span><%= link "Back", to: Routes.page_path(@conn, :index), class: "btn btn-secondary" %></span>

<div>
    <br/>
    <h4>Responses:</h4>
    <dl>
        <dd><strong>Yes: </strong><%= @num_yes %></dd>
        <dd><strong>Maybe: </strong><%= @num_maybe %></dd>
        <dd><strong>No: </strong><%= @num_no %></dd>
        <dd><strong>Haven't Responded: </strong><%= @num_havent %></dd>
    </dl>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Invitee</th>
            <th scope="col">Response</th>
        </tr>
        </thead>
        <tbody>
        <%= for invite <- @invites do %>
        <tr>
            <td><%= invite.invitee %> </td>
            <td><%= invite.response %></td>
        </tr>
        <% end %>
        </tbody>
    </table>
</div>


<div>
    <%= if Events.CalEvents.is_invitee?(@event.id, @conn.assigns[:current_user]) do
 link("New Comment", to: Routes.comment_path(@conn, :new, %{event_id: @event.id}), class: "btn btn-secondary")
 end %>

    <div class="container">
        <br/>
        <div class="row row-cols-1 row-cols-md-2 g-4">
        <%= for {comment, user} <- @comment_details do %>
            <div class="col mb-3">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Author: <%= user.name %></p>
                        <p class="card-text"><%= comment.text %></p>
                        <%= if Events.Comments.is_author?(comment.id, @conn.assigns[:current_user]) or
                               Events.CalEvents.is_owner?(@event.id, @conn.assigns[:current_user])
                         do
                          link "Delete", to: Routes.comment_path(@conn, :delete, comment), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-outline-danger"
                        end %>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
        <br/>
    </div>
</div>
<% else %>
<p><strong>Login or Register to view event if authorized</strong></p>
<% end %>