hw08/events/lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router


  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.FetchSession

  end

  pipeline :api do
    plug :accepts, ["json"]
  end



  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/events", EventController
    resources "/invites", InviteController,
      only: [:edit, :create, :new, :index, :update]
    resources "/comments", CommentController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

hw08/events/lib/events_web/templates/page/index.html.eex
<div class="row">
    <div class="column">
        <h1 class="display-4">Home</h1>
    </div>
</div>

<div class="row form-group">
    <div class="col-sm-1">
    <%= link("Events", to: Routes.event_path(@conn, :index), class: "btn btn-secondary") %>
    </div>
</div>

<div class="row-cols-xl-1">
    <br/>
    <h4>Events:</h4>
    <%= for event <- @events do %>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><%= event.name %></h5>
                <p class="card-text"><%= event.date %></p>
                <p class="card-text"><%= event.description %></p>
                <%= link("view", to: Routes.event_path(@conn, :show, event)) %>
            </div>
        </div>
    </div>
    <% end %>
</div>


<div class="row-cols-xl-1">
    <br/>
    <h4>Invites:</h4>
    <%= for {i, e} <- @invites do %>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Name: <%= e.name %></h5>
                <p class="card-text">Date: <%= e.date %></p>
                <p class="card-text">Response: <%= i.response %></p>
                <%= link("view", to: Routes.event_path(@conn, :show, e)) %>
            </div>
        </div>
    </div>
    <% end %>
</div>