hw08/events/lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router


  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.FetchSession

  end

  pipeline :api do
    plug :accepts, ["json"]
  end



  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/events", EventController
    resources "/invites", InviteController,
      only: [:edit, :create, :new, :index, :update]
    resources "/comments", CommentController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

hw08/events/lib/events/comments.ex
defmodule Events.Comments do
  @moduledoc """
  The Comments context.
  """

  import Ecto.Query, warn: false
  alias Events.Repo

  alias Events.Comments.Comment

  @doc """
  Returns the list of comments.

  ## Examples

      iex> list_comments()
      [%Comment{}, ...]

  """
  def list_comments do
    Repo.all(Comment)
  end

  def list_comments_for_event(id) do
    query = from c in Comment,
                 where: c.event_id == ^id

    Repo.all(query)
  end

  @doc """
  Gets a single comment.

  Raises `Ecto.NoResultsError` if the Comment does not exist.

  ## Examples

      iex> get_comment!(123)
      %Comment{}

      iex> get_comment!(456)
      ** (Ecto.NoResultsError)

  """
  def get_comment!(id), do: Repo.get!(Comment, id)

  @doc """
  Creates a comment.

  ## Examples

      iex> create_comment(%{field: value})
      {:ok, %Comment{}}

      iex> create_comment(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_comment(attrs \\ %{}) do
    %Comment{}
    |> Comment.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a comment.

  ## Examples

      iex> update_comment(comment, %{field: new_value})
      {:ok, %Comment{}}

      iex> update_comment(comment, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_comment(%Comment{} = comment, attrs) do
    comment
    |> Comment.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a comment.

  ## Examples

      iex> delete_comment(comment)
      {:ok, %Comment{}}

      iex> delete_comment(comment)
      {:error, %Ecto.Changeset{}}

  """
  def delete_comment(%Comment{} = comment) do
    Repo.delete(comment)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking comment changes.

  ## Examples

      iex> change_comment(comment)
      %Ecto.Changeset{data: %Comment{}}

  """
  def change_comment(%Comment{} = comment, attrs \\ %{}) do
    Comment.changeset(comment, attrs)
  end

  def is_author?(comment_id, user) do
    if user == nil do
      false
    else
      comment = get_comment!(comment_id)
      comment.user_id == user.id
    end
  end
end

hw08/events/lib/events/comments/comment.ex
defmodule Events.Comments.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :text, :string
    field :event_id, :id
    field :user_id, :id

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:text, :event_id, :user_id])
    |> validate_required([:text, :event_id, :user_id])
  end
end

hw08/events/lib/events_web/controllers/comment_controller.ex
defmodule EventsWeb.CommentController do
  use EventsWeb, :controller

  alias Events.Comments
  alias Events.Comments.Comment

  def index(conn, _params) do
    redirect(conn, to: Routes.page_path(conn, :index))
  end

  def new(conn, params) do
    if conn.assigns[:current_user] == nil do
      conn
      |> put_flash(:error, "Log in or register")
      |> redirect(to: Routes.page_path(conn, :index))
    end
    event_id = params["event_id"]
    changeset = Comments.change_comment(%Comment{})
    render(conn, "new.html", changeset: changeset, event_id: event_id)
  end

  def create(conn, %{"comment" => comment_params}) do
    case Comments.create_comment(comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, comment.event_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    render(conn, "show.html", comment: comment)
  end

  def edit(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    changeset = Comments.change_comment(comment)
    render(conn, "edit.html", comment: comment, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params}) do
    comment = Comments.get_comment!(id)

    case Comments.update_comment(comment, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, comment.event_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    {:ok, _comment} = Comments.delete_comment(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :show, comment.event_id))
  end
end

hw08/events/lib/events_web/views/comment_view.ex
defmodule EventsWeb.CommentView do
  use EventsWeb, :view
end

hw08/events/lib/events_web/templates/comment/edit.html.eex
<h1>Edit Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :update, @comment)) %>

<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>

hw08/events/lib/events_web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>

<div class="form-group">
    <%= hidden_input f, :event_id, value: assigns[:event_id] %>
    <%= hidden_input f, :user_id, value: @conn.assigns[:current_user].id %>
    <%= label f, :text, class: "col-form-label" %>
    <%= textarea f, :text, class: "form-control"%>
    <%= error_tag f, :text %>
</div>

<div>
    <%= submit "Save", class: "btn btn-primary" %>
</div>
<% end %>

hw08/events/lib/events_web/templates/comment/index.html.eex
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for comment <- @comments do %>
    <tr>
      <td><%= comment.text %></td>

      <td>
        <span><%= link "Show", to: Routes.comment_path(@conn, :show, comment) %></span>
        <span><%= link "Edit", to: Routes.comment_path(@conn, :edit, comment) %></span>
        <span><%= link "Delete", to: Routes.comment_path(@conn, :delete, comment), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Comment", to: Routes.comment_path(@conn, :new) %></span>

hw08/events/lib/events_web/templates/comment/new.html.eex
<h1>New Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :create)) %>

<br/>
<span><%= link "Back", to: Routes.event_path(@conn, :show, @event_id), class: "btn btn-secondary" %></span>

hw08/events/lib/events_web/templates/comment/show.html.eex
<h1>Show Comment</h1>

<ul>

  <li>
    <strong>Text:</strong>
    <%= @comment.text %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.comment_path(@conn, :edit, @comment) %></span>
<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>