hw08/events/lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router


  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.FetchSession

  end

  pipeline :api do
    plug :accepts, ["json"]
  end



  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/events", EventController
    resources "/invites", InviteController,
      only: [:edit, :create, :new, :index, :update]
    resources "/comments", CommentController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

hw08/events/lib/events_web/views/layout_view.ex
defmodule EventsWeb.LayoutView do
  use EventsWeb, :view
end

hw08/events/lib/events_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Events · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>
<body>
<header>
    <div role="main" class="container">
        <div class="row">
            <div class="col">
                <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <p><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></p>
                <% end %>
            </div>
            <%= if @conn.assigns[:current_user] do %>
            <div>
                User: <%= @current_user.name %>
                <%= link("Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary")%>
            </div>
            <% else %>
            <div class="col">
                <%= form_for @conn, Routes.session_path(@conn, :create),
                [class: "form-inline"], fn f -> %>
                <div class="form-group">
                    <%= text_input f, :email, class: "form-control" %>
                    <%= submit "Login", class: "btn btn-primary"%>
                </div>
            </div>
            <% end %>
            <div class="col">
                <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn btn-secondary"%>
            </div>
            <% end %>
        </div>
    </div>
</header>
<main role="main" class="container">
    <%= if get_flash(@conn, :info) do %>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>

    <%= if get_flash(@conn, :error) do %>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>

    <%= @inner_content %>
</main>
</body>
</html>